version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: music_ai_2
    restart: unless-stopped
    volumes:
      - ./Mysql:/var/lib/mysql
      - ./source/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3100:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}



