version: "3"

services:
  mysql:
    image: mysql:latest 
    container_name: MySQL
    restart: unless-stopped 
    volumes:
      - ./Mysql:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3100:3306
    environment:
      - MYSQL_ROOT_PASSWORD=song

      
    image: mysql:latest
    container_name: MIML
    restart: unless-stopped
    volumes:
      - ./Mysql:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
